export const CONFIG = {
	SHOPIFY_STORE_DOMAIN: process.env.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN,
	SHOPIFY_STOREFRONT_API_URL: process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_API_URL,
	SHOPIFY_STOREFRONT_ACCESS_TOKEN: process.env.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN,
};
